# Generated by Django 4.2.3 on 2023-09-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Accounts', '0001_initial'),
        ('Quiz_Section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quizzes',
            field=models.ManyToManyField(related_name='users', through='Accounts.ResultatQuiz', to='Quiz_Section.quiz'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='semestres',
            field=models.ManyToManyField(related_name='users', through='Accounts.Membership', to='Accounts.semestre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='faculte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.faculte'),
        ),
        migrations.AddField(
            model_name='resultatquiz',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultatquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.quiz'),
        ),
        migrations.AddField(
            model_name='membership',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.semestre'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
