# Generated by Django 4.2.3 on 2023-09-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('NL', 'Normal'), ('RAT', 'Rattrapage'), ('EXP', 'Exceptionnel')], max_length=3)),
                ('annee', models.CharField(max_length=4)),
                ('correction', models.CharField(choices=[('Off', 'Officiel'), ('Col', 'Collective'), ('Non', 'Non Disponible')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='Accounts.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('Qcorrection', models.BooleanField(default=True)),
                ('Qtype', models.CharField(choices=[('Mult', 'Multiple'), ('text', 'Ordonnance & CROC'), ('img', 'Dessin')], max_length=4)),
                ('ordre', models.PositiveSmallIntegerField()),
                ('examInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz_Section.examinfo')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreQuestions', models.IntegerField(default=50)),
                ('questions', models.ManyToManyField(blank=True, related_name='quizzes', to='Quiz_Section.question')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ordre', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='Quiz_Section.question')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SousModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_modules', to='Quiz_Section.module')),
            ],
        ),
        migrations.CreateModel(
            name='SavedQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz_Section.module')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.question')),
                ('sous_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz_Section.sousmodule')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.quiz')),
                ('rep', models.ManyToManyField(to='Quiz_Section.reponse')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='scenarios',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='Quiz_Section.scenario'),
        ),
        migrations.AddField(
            model_name='question',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='Quiz_Section.scenario'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.question')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('sous_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Quiz_Section.sousmodule')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.question')),
            ],
        ),
        migrations.CreateModel(
            name='SMQuiz',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quiz_Section.quiz')),
                ('examinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz_Section.examinfo')),
                ('sousModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.sousmodule')),
            ],
            bases=('Quiz_Section.quiz',),
        ),
        migrations.CreateModel(
            name='ModuleQuiz',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quiz_Section.quiz')),
                ('examinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz_Section.examinfo')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulequizzes', to='Quiz_Section.module')),
            ],
            bases=('Quiz_Section.quiz',),
        ),
        migrations.CreateModel(
            name='CoursQuiz',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quiz_Section.quiz')),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.cours')),
            ],
            bases=('Quiz_Section.quiz',),
        ),
        migrations.CreateModel(
            name='CasClinique',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quiz_Section.quiz')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Section.module')),
            ],
            bases=('Quiz_Section.quiz',),
        ),
    ]
